In [7]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import sys

sys.path.append('/Users/aashnashah/Desktop/ssh_mount/SETPOINT/')
from setpoint import calculate_setpoint, process_data, process_dataframe
from data_process.processors.cbc import CBC_REFERENCE_INTERVALS

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
# Setpoint calculation for each subject and code 
x = [36, 438, 766, 949, 1168, 1606, 2044 ,2518, 2701, 3139, 3540, 4088, 4708]
y = [280, 312, 331, 297, 326, 342, 301, 288, 305, 296, 415, 300, 335]

setpoint_df = calculate_setpoint(x, y)
display(setpoint_df)

(309.41666666764917, 0.06118517244538388, 'gmm')

In [12]:
# df = pd.read_csv('data/subject_cbc_events.csv')
# df_sample = df.sort_values(by=['subject_id', 'time'])

# # Process each group
# setpoints = []
# for (subject, code), group in df_sample.groupby(['subject_id', 'code']):
#     if not group.empty:
#         x, y = process_dataframe(group)
#         setpoint, uncertainty, model = calculate_setpoint(x, y)
        
#         if model != "insufficient_data":
#             setpoints.append({
#                 'subject_id': subject,
#                 'code': code,
#                 'setpoint': setpoint,
#                 'uncertainty': uncertainty,
#                 'model_type': model
#             })

# # Save results
# if setpoints:
#     setpoint_df = pd.DataFrame(setpoints)
#     setpoint_df.to_csv(
#         f'data/setpoint_cbc_events_{len(setpoints)}.csv', 
#         index=False
#     )
#     print(f"Found {len(setpoints)} setpoints")

In [86]:
setpoint_df

      subject_id  code    setpoint  uncertainty   model_type
0      115967125   HCT   38.275000     0.008932          gmm
1      115967125   HGB   12.950002     0.011584          gmm
2      115967125   MCH   31.192892     0.025431          gmm
3      115967125  MCHC   33.657171     0.011102          gmm
4      115967125   MCV   94.650000     0.013880          gmm
...          ...   ...         ...          ...          ...
5235   115973825  MCHC   33.679939     0.003463          gmm
5236   115973825   MCV   87.799979     0.005897          gmm
5237   115973825   PLT  326.272727     0.128269  statistical
5238   115973825   RBC    5.403689     0.026539          gmm
5239   115973825   RDW   12.700276     0.013212          gmm

[5240 rows x 5 columns]

In [62]:
cbc_subject_stats = pd.read_csv('../data/summary_statistics/cbc_subject_statistics.csv')
cbc_subject_stats

setpoint_df = pd.read_csv('../data/setpoint_calculations/setpoints_gap:90_tests:5.csv')
display(setpoint_df.head())

demographics_df = pd.read_csv('../data/processed/demographics.csv')

merged = pd.merge(setpoint_df, cbc_subject_stats, on=['subject_id', 'code'], how='left')
setpoint_df = pd.merge(merged, demographics_df, on='subject_id', how='left')
display(merged.head())

   subject_id  code   setpoint  uncertainty model_type
0   115967125   HCT  38.275000     0.008932        gmm
1   115967125   HGB  12.950002     0.011584        gmm
2   115967125   MCH  31.192892     0.025431        gmm
3   115967125  MCHC  33.657171     0.011102        gmm
4   115967125   MCV  94.650000     0.013880        gmm

,subject_id,code,setpoint,uncertainty,model_type,num_tests_taken,num_tests_within_reference,percentage_tests_within_reference,days_between_first_and_last,avg_days_between_tests,min_days_between_tests,max_days_between_tests
0,115967125,HCT,38.275000,0.008932,gmm,36,24,66.67%,6294,179.86,0.1,2168.16
1,115967125,HGB,12.950002,0.011584,gmm,36,27,75.00%,6294,179.86,0.1,2168.16
2,115967125,MCH,31.192892,0.025431,gmm,36,25,69.44%,6294,179.86,0.1,2168.16
3,115967125,MCHC,33.657171,0.011102,gmm,36,36,100.00%,6294,179.86,0.1,2168.16
4,115967125,MCV,94.650000,0.013880,gmm,36,32,88.89%,6294,179.86,0.1,2168.16

In [53]:
CBC_REFERENCE_INTERVALS

{'HCT': {'F': (36, 46, '%'), 'M': (41, 53, '%')},
 'HGB': {'F': (12.0, 16.0, 'g/dL'), 'M': (13.5, 17.5, 'g/dL')},
 'MCH': {'F': (26, 34, 'pg'), 'M': (26, 34, 'pg')},
 'MCHC': {'F': (31, 37, 'g/dL'), 'M': (31, 37, 'g/dL')},
 'MPV': {'F': (8.4, 12.0, 'fL'), 'M': (8.4, 12.0, 'fL')},
 'PLT': {'F': (150, 400, '10³/µL'), 'M': (150, 400, '10³/µL')},
 'RBC': {'F': (4.0, 5.2, '10⁶/µL'), 'M': (4.5, 5.9, '10⁶/µL')},
 'RDW': {'F': (11.5, 14.5, '%'), 'M': (11.5, 14.5, '%')},
 'WBC': {'F': (4.5, 11.0, '10³/µL'), 'M': (4.5, 11.0, '10³/µL')},
 'MCV': {'F': (80, 100, 'fL'), 'M': (80, 100, 'fL')}}